/**
 * What a consumer can actually import.
 *
 * `files` and `exports` are two independent gates and they failed independently. On
 * 2026-09-09 `execution.js` was listed in `files` but absent from `exports`, so the module
 * shipped inside the tarball and `import '@packvium/engine/execution.js'` still threw
 * `ERR_PACKAGE_PATH_NOT_EXPORTED` — a documented public entry point that no consumer could
 * reach. Nothing in the suite noticed, because every in-repo caller uses a relative path
 * (`../execution.js`), which bypasses `exports` entirely.
 *
 * So these tests import by *package name*. A self-reference resolves through the real
 * `exports` map, which is the gate the relative paths never touch.
 */
import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const PACKAGE_ROOT = path.dirname(path.dirname(fileURLToPath(import.meta.url)));
const manifest = JSON.parse(fs.readFileSync(path.join(PACKAGE_ROOT, 'package.json'), 'utf8'));

test('the main entry resolves by package name and carries the packing surface', async () => {
  const main = await import(manifest.name);
  for (const name of ['pack', 'packJson', 'rebalanceWeight', 'commerce', 'backend']) {
    assert.equal(typeof main[name], name === 'commerce' ? 'object' : 'function', name);
  }
});

test('the execution plan resolves by package name, not only by relative path', async () => {
  const execution = await import(`${manifest.name}/execution.js`);
  assert.equal(typeof execution.buildExecutionPlan, 'function');
  assert.equal(typeof execution.canonicalPlanJson, 'function');
  assert.equal(typeof execution.placementReference, 'function');
  assert.equal(execution.FORMAT, 'packvium-execution-plan/v1');
});

test('the operational artifact and its exports resolve by package name', async () => {
  const artifacts = await import(`${manifest.name}/artifacts.js`);
  assert.equal(typeof artifacts.buildOperationalArtifact, 'function');
  assert.equal(typeof artifacts.canonicalArtifactJson, 'function');
  assert.equal(typeof artifacts.OperationalArtifactError, 'function');
  assert.equal(artifacts.FORMAT, 'packvium-operational-artifact/v1');
  const exports = await import(`${manifest.name}/artifact-exports.js`);
  for (const name of ['exportJson', 'exportCsv', 'exportWorkOrderHtml']) {
    assert.equal(typeof exports[name], 'function', name);
  }
  assert.equal(exports.CSV_COLUMNS[0], 'record');
});

test('a module an export imports is published even when it is not exported itself', () => {
  // `canonical-json.js` is internal: absent from `exports` on purpose, but `artifacts.js` and
  // `execution.js` import it, so a tarball without it would break both at load time.
  const published = new Set(manifest.files);
  for (const name of ['canonical-json.js', 'artifacts.js', 'artifact-exports.js', 'artifacts.d.ts', 'artifact-exports.d.ts']) {
    assert.ok(published.has(name), `"files" does not publish ${name}`);
  }
  assert.ok(!('./canonical-json.js' in manifest.exports), 'canonical-json.js is not public API');
});

test('every declared export target exists, and so does the types file beside it', () => {
  for (const [subpath, entry] of Object.entries(manifest.exports)) {
    for (const [condition, target] of Object.entries(entry)) {
      const resolved = path.join(PACKAGE_ROOT, target);
      assert.ok(fs.existsSync(resolved),
        `exports["${subpath}"].${condition} points at ${target}, which does not exist`);
    }
  }
});

test('every exported subpath is also published', () => {
  // `files` decides what is in the tarball; `exports` decides what can be imported from it.
  // A subpath present in one and missing from the other is broken either way round.
  const published = new Set(manifest.files);
  for (const subpath of Object.keys(manifest.exports)) {
    if (subpath === '.') continue;
    for (const target of Object.values(manifest.exports[subpath])) {
      const name = target.replace(/^\.\//, '');
      assert.ok(published.has(name),
        `exports names ${name}, which "files" does not publish — it would be missing from the tarball`);
    }
  }
});

// Written into every package by `scripts/export-public.py` rather than kept in the source
// tree, so their absence here is correct and their presence in the tarball is not this
// test's business.
const GENERATED_AT_EXPORT = new Set(['SECURITY.md', 'CHANGELOG.md', 'CONTRIBUTING.md']);

test('every published file exists in the source tree or is generated by the export', () => {
  for (const entry of manifest.files) {
    if (GENERATED_AT_EXPORT.has(entry)) continue;
    assert.ok(fs.existsSync(path.join(PACKAGE_ROOT, entry)),
      `"files" publishes ${entry}, which does not exist`);
  }
});
